package org.example.enums;

public enum EncryptionEvents {
    ENCRYPT,
    DECRYPT,
    ENCRYPTION_FILE,
    DECRYPTION_FILE,
    ENCRYPTION_DIRECTORY,
    DECRYPTION_DIRECTORY,
    ENCRYPTION_DIRECTORY_STARTED,
    ENCRYPTION_DIRECTORY_ENDED,
    DECRYPTION_DIRECTORY_STARTED,
    DECRYPTION_DIRECTORY_ENDED,
    ENCRYPTION_FILE_STARTED,
    ENCRYPTION_FILE_ENDED,
    DECRYPTION_FILE_STARTED,
    DECRYPTION_FILE_ENDED,
    KEY_FOR_FILE,
    KEY_FOR_DIRECTORY,
    KEY_FILE_CREATED


}
